import axios from 'axios';
import { CLIError } from '../core/errors.js';

/**
 * Call the selected LLM API to generate content.
 * 
 * Supports Gemini, OpenAI, and Anthropic API keys.
 * 
 * @param {string} prompt - The prompt text.
 * @param {string} [modelName] - Optional override for the model.
 * @returns {Promise<string>} The string content generated by the LLM.
 */
export async function callLLM(prompt, modelName) {
  if (process.env.MOCK_LLM_RESPONSE) {
    return process.env.MOCK_LLM_RESPONSE;
  }

  const geminiKey = process.env.GEMINI_API_KEY;
  const openaiKey = process.env.OPENAI_API_KEY;
  const anthropicKey = process.env.ANTHROPIC_API_KEY;

  if (geminiKey) {
    const model = modelName || 'gemini-2.5-flash';
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${geminiKey}`;

    try {
      const response = await axios.post(url, {
        contents: [
          {
            parts: [{ text: prompt }]
          }
        ],
        generationConfig: {
          responseMimeType: 'application/json'
        }
      }, {
        headers: {
          'Content-Type': 'application/json'
        }
      });

      const text = response.data?.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) {
        throw new Error('Empty response from Gemini API.');
      }
      return text;
    } catch (err) {
      const detail = err.response?.data?.error?.message || err.message;
      throw new CLIError(`Gemini API call failed: ${detail}`);
    }
  }

  if (openaiKey) {
    const model = modelName || 'gpt-4o-mini';
    const url = 'https://api.openai.com/v1/chat/completions';

    try {
      const response = await axios.post(url, {
        model,
        messages: [
          { role: 'user', content: prompt }
        ],
        response_format: { type: 'json_object' }
      }, {
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${openaiKey}`
        }
      });

      const text = response.data?.choices?.[0]?.message?.content;
      if (!text) {
        throw new Error('Empty response from OpenAI API.');
      }
      return text;
    } catch (err) {
      const detail = err.response?.data?.error?.message || err.message;
      throw new CLIError(`OpenAI API call failed: ${detail}`);
    }
  }

  if (anthropicKey) {
    const model = modelName || 'claude-3-5-sonnet-20241022';
    const url = 'https://api.anthropic.com/v1/messages';

    try {
      const response = await axios.post(url, {
        model,
        max_tokens: 4000,
        messages: [
          { role: 'user', content: prompt }
        ]
      }, {
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': anthropicKey,
          'anthropic-version': '2023-06-01'
        }
      });

      const text = response.data?.content?.[0]?.text;
      if (!text) {
        throw new Error('Empty response from Anthropic API.');
      }
      return text;
    } catch (err) {
      const detail = err.response?.data?.error?.message || err.message;
      throw new CLIError(`Anthropic API call failed: ${detail}`);
    }
  }

  throw new CLIError(
    'No LLM API Key detected.\n' +
    'Please set one of the following environment variables:\n' +
    '  - GEMINI_API_KEY (for Gemini)\n' +
    '  - OPENAI_API_KEY (for OpenAI)\n' +
    '  - ANTHROPIC_API_KEY (for Anthropic)'
  );
}
